dist: trusty
language: java
# sudo: false
# addons:
#   apt:
#     packages:
#       - oracle-java8-installer
#       - oracle-java9-installer
#       - oracle-java10-installer
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk11
